Support unicode message in ClientSideError
This change add support to unicode message in ClientSideError.
Before the change a UnicodeEncodeError is raised when a unicode string is used
in a ClientSideError Exception:

Traceback (most recent call last):
  File "/data/os_dev/stack-master/wsme/.tox/py27/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data/os_dev/stack-master/wsme/wsme/tests/test_exc.py", line 16, in test_unicode_clientside_error
    assert e.faultstring == u("\u30d5\u30a1\u30b7\u30ea")
  File "/data/os_dev/stack-master/wsme/wsme/exc.py", line 12, in faultstring
    return str(self)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

--HG--
branch : sileht/unicode-clientsideerror